### ISSUE TITLE
4.0.0 update causes "Uncaught TypeError: LocomotiveScroll is not a constructor"

### ISSUE THREAD

**Issue by elliottmangham** [locomotivemtl/locomotive-scroll#187]
Hello 👋

**Describe the bug**
Since version 4.0.0 the non-bundler instantiation has stopped working. I now get a console error:
`Uncaught TypeError: LocomotiveScroll is not a constructor`

**To Reproduce**
Instantiate without a bundler as per instruction. Note I am also using jQuery.
```
<script src="locomotive-scroll.min.js"></script>
<script>
    (function ( $ ) {
        'use strict';
        var scroll = new LocomotiveScroll( {
                el: document.querySelector( '[data-scroll-container]' ),
                smooth: true
        } );
    })();
</script>
```

**Expected behavior**
This worked prior to version 4.0.0 update.

**Screenshots**
![Screenshot 2020-11-17 085423](https://user-images.githubusercontent.com/12933804/99368004-8ffdd980-28b2-11eb-9f12-2803cceb7398.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome 86.0.4240.198

Thank you 👊 Really appreciate the help!

**Comment by amashuroff** [comment]
Same here.

**Comment by adambushell-dev** [comment]
Yea im seeing this as well

**Comment by antoineboulanger** [comment]
Hey guys, It should be fixed in 4.0.2. Let me know if it's working for you.

**Comment by elliottmangham** [comment]
> Hey guys, It should be fixed in 4.0.2. Let me know if it's working for you.

Hey @antoineboulanger, I just tested and unfortunately, this doesn't seem to work. I've included the new JS+CSS and cleared cache but I'm still getting the `LocomotiveScroll is not a constructor`.

Thank you

**Comment by mrkbr** [comment]
Same here on 4.0.2

**Comment by antoineboulanger** [comment]
I found the other problem. It's now fixed in 4.0.3. Thanks.

**Comment by mrkbr** [comment]
Yes I can confirm that.

**Comment by coderesolution** [comment]
It is working for me also! Thanks so much, @antoineboulanger.

**Comment by elliottmangham** [comment]
It is working for me also! Thanks so much, @antoineboulanger.

**Comment by pratham5368** [comment]
i am still stuck

**Comment by elliottmangham** [comment]
@pratham5368, this is an old thread, so it doesn't get ignored you'll need to give more context of the issue, current version, error and code example.
