### ISSUE TITLE
Scroll does not work on desktop touch screen devices

### ISSUE THREAD

**Issue by htmlburger-git** [locomotivemtl/locomotive-scroll#69]
Hello 👋

**Describe the bug**
The touch scroll triggers are completely ignored on desktop touch screen devices. Nothing will happen if the users scroll using touch gestures.

**Expected behavior**
Behave as on normal pages - being able to scroll up/down using touch gestures.

Thank you 👊

**Comment by Barido** [comment]
Actually just run into the same issue for Microsoft Surface users on latest Edge or IE you can't scroll at all with the either touchscreen or touchpad which isn't a fantastic result. Anyone have a work around for this?

**Comment by antoineboulanger** [comment]
Hi, for the trackpad problem on IE and Edge,  its a known issue since forever that scroll events do not work on precision trackpads. Fortunately, Edge is switching to Chromium and that should finally be fixed. Release date: January 15.

For the touch screen issue, what browser are you using @htmlburger-git? Does it work on Chrome?

**Comment by htmlburger-git** [comment]
Hey, the issue is actually on Microsoft Surface and any other desktop device (laptop) with a touch screen. 

It doesn't matter what the browser is. The touch events are ignored when you try to scroll by touching the monitor.

**Comment by antoineboulanger** [comment]
Should be fixed ✌️

**Comment by roomfive** [comment]
This is still an issue... 

Even [the Locomotive Scroll example website](https://locomotivemtl.github.io/locomotive-scroll/) doesn't work on a Microsoft Surface in the Edge browser, or [locomotive.ca](https://locomotive.ca/), or any of the "[Who's using Locomotive Scroll](https://github.com/locomotivemtl/locomotive-scroll#whos-using-locomotive-scroll)" example websites on the GitHub page.

P.S. It works in Chrome and Internet Explorer _(figures)_ on a Microsoft Surface, just not Edge.

Any ideas on a fix, please?

**Comment by akshayknz** [comment]
The locomotive scroll official website is not working in chrome mobile or desktop touch (devtools). Same for any website using locomotive scroll

**Comment by samuelgoddard** [comment]
This is still a bug as far as I can tell, client is experiencing this on a Microsoft Surface, should this issue be re-opened?

**Comment by michellekondou** [comment]
I am also getting this bug, can this issue be re-opened? This is a project stopper unfortunately.

**Comment by P2070** [comment]
> I am also getting this bug, can this issue be re-opened? This is a project stopper unfortunately.

Make sure you have added smartphone and tablet.

<script>
	const scroll = new LocomotiveScroll({
		el: document.querySelector('[data-scroll-container]'),
		smooth: true,
		smartphone: {
			smooth: true
		},
		tablet: {
			smooth: true
		}
	});
</script>
